//
//  PostDetailPresenter.swift
//  SocialMedia
//
//  Created by Yeşim Daşdemir on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostDetailPresentationLogic {
    func presentPostDetail(viewModel: PostDetailViewModel)
}

final class PostDetailPresenter: PostDetailPresentationLogic {
    weak var viewController: PostDetailDisplayLogic?
    
    private var commentCount: Int = 0
    
    func presentPostDetail(viewModel: PostDetailViewModel) {
        var tableViewRows: [PostDetailTableViewRows] = []
        
        if let userViewModel = viewModel.userViewModel {
            let singleImageViewModel =  SingleImageViewModel(id: userViewModel.id,
                                            iconName: "share-post",
                                                             title: userViewModel.name?.capitalized)
            
            tableViewRows.append(.profileCell(viewModel: singleImageViewModel))
        }
        
        if let description: String = viewModel.postDescription {
            let singleImageViewModel = SimpleItemViewModel(subTitle: description.capitalized)
            tableViewRows.append(.descriptionCell(description: singleImageViewModel))
        }
           
        if let commentsModel = viewModel.commentsViewModel {
            tableViewRows.append(.commentSummaryCell(viewModel: SimpleItemViewModel(title: "\(commentsModel.count) Comments", iconName: "dots")))
            
            commentCount = commentsModel.count
            
            for item in commentsModel {
                tableViewRows.append(.commentCell(viewModel: SimpleItemViewModel(id: item.id,
                                                                                 title: item.description,
                                                                                 iconName: "comment")))
            }
        }
        viewController?.displayPostDetail(rowList: tableViewRows, commentCount: commentCount)
    }
}
