//
//  PostDetailModels.swift
//  SocialMedia
//
//  Created by Yeşim Daşdemir on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PostDetail {
    // MARK: Use cases
    
    enum GetUsers {
        struct Request: Codable {
            let transactionUrl: String
            
            init() {
                self.transactionUrl = "http://jsonplaceholder.typicode.com/users"
            }
        }
        
        struct Response: Codable {
            let id: Int
            let name: String?
            let username: String?
            let email: String?
        }
    }
    
    enum GetComments {
        struct Request: Codable {
            let transactionUrl: String
            
            init() {
                self.transactionUrl = "http://jsonplaceholder.typicode.com/comments"
            }
        }
        
        struct Response: Codable {
            let id: Int
            let postId: Int?
            let name: String?
            let email: String?
            let description: String?
            
            enum CodingKeys: String, CodingKey {
                case id
                case postId
                case name
                case email
                case description = "body"
            }
        }
    }
}

struct PostDetailViewModel {
    let userViewModel: PostDetail.GetUsers.Response?
    let commentsViewModel: [PostDetail.GetComments.Response]?
    let postDescription: String?
}

enum PostDetailTableViewRows {
    case profileCell(viewModel: SingleImageViewModel?)
    case descriptionCell(description: SimpleItemViewModel?)
    case commentSummaryCell(viewModel: SimpleItemViewModel?)
    case commentCell(viewModel: SimpleItemViewModel?)
}
