//
//  PostDetailInteractor.swift
//  SocialMedia
//
//  Created by Yeşim Daşdemir on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostDetailBusinessLogic {
}

protocol PostDetailDataStore {
    var selectedPostModel: SimpleItemViewModel? { get set }
}

final class PostDetailInteractor: PostDetailBusinessLogic, PostDetailDataStore {
    
    var presenter: PostDetailPresentationLogic?
    var worker: PostDetailWorker?
    var selectedPostModel: SimpleItemViewModel?
    
}
