//
//  PostDetailModels.swift
//  SocialMedia
//
//  Created by Yeşim Daşdemir on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PostDetail {
  // MARK: Use cases
  
  enum Something {
    struct Request {
    }
      
    struct Response {
    }
      
    struct ViewModel {
    }
  }
}
