//
//  PostListRouter.swift
//  SocialMedia
//
//  Created by Yeşim Daşdemir on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PostListRoutingLogic {

}

protocol PostListDataPassing {
  var dataStore: PostListDataStore? { get }
}

final class PostListRouter: NSObject, PostListRoutingLogic, PostListDataPassing {
  weak var viewController: PostListViewController?
  var dataStore: PostListDataStore?
  
  // MARK: Routing
  

  // MARK: Navigation
  
  //func navigateToSomewhere(source: PostListViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: PostListDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
