//
//  PostListPresenter.swift
//  SocialMedia
//
//  Created by Yeşim Daşdemir on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostListPresentationLogic {
    func presentPostList(with response: [PostList.GetPosts.Response])
}

final class PostListPresenter: PostListPresentationLogic {
    weak var viewController: PostListDisplayLogic?
    
    func presentPostList(with response: [PostList.GetPosts.Response]) {
        let viewModel = response.map { response in
            return SimpleItemViewModel(id: response.id,
                                       userId: response.userId,
                                       title: response.title.uppercased(),
                                       subTitle: response.body.capitalized,
                                       iconName: "profile")
        }
        
        viewController?.displayPostList(viewModel: viewModel)
    }
}
