//
//  PostListModels.swift
//  SocialMedia
//
//  Created by Yeşim Daşdemir on 21.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PostList {
    // MARK: Use cases
    
    enum GetPostList {
        struct Request: Codable {
            let transactionUrl: String
            
            init() {
                self.transactionUrl = "http://jsonplaceholder.typicode.com/posts"
            }
        }
        
        struct Response: Codable {
            let userId: Int
            let id: Int
            let title: String
            let body: String
        }
        
        struct ViewModel {
        }
    }
}
